"""empty message

Revision ID: f49f08e77ed5
Revises: f484298d9b7b
Create Date: 2019-03-26 22:27:17.726994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49f08e77ed5'
down_revision = 'f484298d9b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('finished', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'finished')
    # ### end Alembic commands ###
